### ISSUE TITLE
Link fix in der readme

### ISSUE THREAD

**Issue by AnsgarHoeper** [gematik/spec-ISiK-Sicherheit#41]
In der readme wird auf eine alte simplifier-Seite verwiesen und läuft ins leere. Die neue ist: https://simplifier.net/spec-isik-sicherheit

**Comment by f-peverali** [comment]
https://github.com/gematik/spec-ISiK-Sicherheit/commit/0fa456dfa1fe8d6dcce927c65afd59964002f715 SOLVED
