### ISSUE TITLE
Compartments und CapabilityStatement

### ISSUE THREAD

**Issue by jcaumann** [gematik/spec-ISiK-Sicherheit#64]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/6bf96362758630833c785f4c410cb383254484cd/ImplementationGuide/markdown/ConformanceScopesKontexte.md?plain=1#L28

MUSS oder SOLL?

**Comment by alexzautke** [comment]
Da die Compartment-Definitionen fix sind kann im CapabilityStatement nicht angegeben werden welche Ressource darüber hinaus ins Compartment mit einbezogen werden. Was wäre der Vorteil die statische Definition hier anzugeben?

**Comment by alexzautke** [comment]
Exponiert irgendein FHIR-Server aktuell dieses Feld out-of-the-box?

**Comment by jcaumann** [comment]
ich habe das in SOLL geändert, da hieran nicht der Einsatz eines kommerziellen FHIR-Servers scheitern sollte (siehe KOmmentar von @alexzautke )
