### ISSUE TITLE
ISIK Kommentierung - authentische Nutzer

### ISSUE THREAD

**Issue by NicoBergeman** [gematik/spec-ISiK-Sicherheit#66]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/99750c51cd1be363c4b0e00bae313b9c9343746b/ImplementationGuide/markdown/Einfuehrung.md?plain=1#LL26C132-L26C132

Müssen Nutzer nicht authentifiziert, statt authentisch sein?

**Comment by JoshuaBolte** [comment]
Korrigiert.
