### ISSUE TITLE
ISIK-Kommentierung - Vorschlag alternative Formulierung

### ISSUE THREAD

**Issue by NicoBergeman** [gematik/spec-ISiK-Sicherheit#75]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/99750c51cd1be363c4b0e00bae313b9c9343746b/ImplementationGuide/markdown/Einfuehrung.md?plain=1#L59

Besser wäre hier: ...die in der Alltagssprache gebräuchliche Form verwendet...

**Comment by JoshuaBolte** [comment]
Korrigiert.
