### ISSUE TITLE
ISIK-Kommentierung - vollständige Erklärung

### ISSUE THREAD

**Issue by NicoBergeman** [gematik/spec-ISiK-Sicherheit#76]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/99750c51cd1be363c4b0e00bae313b9c9343746b/ImplementationGuide/markdown/ReleaseNotes.md?plain=1#L5

Hier wird nur auf Major (erste Stelle) und Bugfix/technische Releases (dritte Stelle) der Versionsnummer Bezug genommen. Wird die zweite Stelle (Minor Changes) gar nicht berücksichtigt/gebraucht?

**Comment by JoshuaBolte** [comment]
Weis ich nicht. @f-peverali weist du das?

**Comment by f-peverali** [comment]
Zweite Stelle benutzen wir nicht. Das können wir nochmal besprechen...

**Comment by NicoBergeman** [comment]
Rechtliche Gründe, kann nicht im Zuge des Moduls ISiK-Sicherheit angegangen werden
