### ISSUE TITLE
ISIK-Kommentierung - Formatierung

### ISSUE THREAD

**Issue by NicoBergeman** [gematik/spec-ISiK-Sicherheit#77]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/99750c51cd1be363c4b0e00bae313b9c9343746b/ImplementationGuide/markdown/ReleaseNotes.md?plain=1#LL36C1-L36C1

Wäre es nicht besser, hier etwas Abstant zum vorausgehenden Text zu lassen, um herauszustellen, dass es sich hierbei nicht um einen Bezug zur ältesten Änderung handelt, sondern das gesamte Changelog eingesehen werden kann?
Ich würde das evtl. sogar an den Anganf setzen und dann darunter erst die letzten Changes posten...

**Comment by JoshuaBolte** [comment]
Korrigiert.
