### ISSUE TITLE
ISIK-Kommentierung - Verständlichkeit

### ISSUE THREAD

**Issue by NicoBergeman** [gematik/spec-ISiK-Sicherheit#81]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/99750c51cd1be363c4b0e00bae313b9c9343746b/ImplementationGuide/markdown/Motivation.md?plain=1#L6

Musste ich mehrmals lesen, um zu verstehen:

"...sondern fokussiert auf den interoperablen Austausch von Informationen zu den für einen gewünschten Zugriff relevanten Autorisierungen..."
Vielleicht besser
"...sondern fokussiert auf den interoperablen Austausch von relevanten Autorisierungsinformationen für einen gewünschten Zugriff..."

**Comment by JoshuaBolte** [comment]
Korrigiert.
