### ISSUE TITLE
ISIK-Kommentierung - Grammatik

### ISSUE THREAD

**Issue by NicoBergeman** [gematik/spec-ISiK-Sicherheit#82]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/99750c51cd1be363c4b0e00bae313b9c9343746b/ImplementationGuide/markdown/Motivation.md?plain=1#LL11C28-L11C32

"Soweit wie möglich" oder "soweit möglich", das "als" suggeriert einen Unterschied...

**Comment by JoshuaBolte** [comment]
Korrigiert.
