### ISSUE TITLE
ISIK-Kommentierung - Aufzählung mit Und

### ISSUE THREAD

**Issue by NicoBergeman** [gematik/spec-ISiK-Sicherheit#83]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/99750c51cd1be363c4b0e00bae313b9c9343746b/ImplementationGuide/markdown/Motivation.md?plain=1#LL11C28-L11C32

Bei Aufzählungen ein und zwischen vorletztem und letztem Eintrag notwendig

**Comment by JoshuaBolte** [comment]
Korrigiert.
