### ISSUE TITLE
ISIK-Kommentierung - Grammatik

### ISSUE THREAD

**Issue by NicoBergeman** [gematik/spec-ISiK-Sicherheit#99]
https://github.com/gematik/spec-ISiK-Sicherheit/blob/72e72fd09a61752ce9e1f18526740f1d2980c3e9/ImplementationGuide/markdown/ISiKAutorisierung.md?plain=1#L82

"können" doppelt im Satz -> ich würde nur das am Ende des Satzes drin lassen.

**Comment by jcaumann** [comment]
erstes "können" gestrichen
